# -*- coding: utf-8 -*-
"""traintestsplit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pEm2QMRUQ-WXLFYjeKlLnJ1Ab1jTJ86W
"""

from sklearn import datasets
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

diabetes = datasets.load_diabetes()

# Split it into features and labels
X = diabetes.data
y = diabetes.target

X.shape

y.shape

# train the model
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)



